<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net11.0-windows</TargetFramework>
    <AssemblyName>WinMintApply</AssemblyName>
    <RootNamespace>WinMint.WinPeApply</RootNamespace>
    <PublishAot Condition="'$(Configuration)' == 'Release'">true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StackTraceSupport>false</StackTraceSupport>
    <OptimizationPreference>Size</OptimizationPreference>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="WinMint.Tests" />
  </ItemGroup>
</Project>
