#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
ENV_FILE="${ENV_FILE:-.scratch/primary-gate.env}"

# Run this from the repo root, via Git Bash or WSL (not plain cmd.exe/pwsh).

banner "WinMint Primary wipe path"

# ── Stage 1: Restore path ──────────────────────────────────────────────────
stage "Restore path"
say "Before the destructive install, have a restore path for THIS PC ready."
say "This is operator hygiene, not a WinMint feature — WinMint never downloads"
say "or ships recovery images (see README)."
open_url "https://support.microsoft.com/surfacerecoveryimage"
step "Surface: grab a serial-matched recovery image (BMR) from the link above."
note "Not a Surface? Use your PC maker's OEM recovery site, or a Windows recovery drive."
note "Maintainer note: a local serial-matched BMR (e.g. under Downloads) is fine for"
note "this device — just never commit or link that file in the repo."
if ! confirm "Restore path ready for this PC?"; then
  warn "Get a restore path sorted before continuing — re-run this wizard when ready."
  exit 1
fi

# ── Stage 2: Password file ─────────────────────────────────────────────────
stage "Password file"
say "samples/sl7.profile.json expects account.passwordPath to resolve to"
say "  .scratch/sl7.password"
say "(WinMint never prints or logs this file's contents.)"
if [[ -f ".scratch/sl7.password" ]]; then
  printf '  %s✓%s .scratch/sl7.password exists\n' "$GREEN" "$RESET"
else
  warn ".scratch/sl7.password not found."
  step "Create it now (repo root): printf '%s' 'yourpassword' > .scratch/sl7.password"
  pause "Press Enter once the file exists"
  if [[ -f ".scratch/sl7.password" ]]; then
    printf '  %s✓%s .scratch/sl7.password exists\n' "$GREEN" "$RESET"
  else
    warn "still missing — the build will fail without it. Continuing anyway."
  fi
fi

# ── Stage 3: Source ISO ─────────────────────────────────────────────────────
stage "Source ISO"
say "Point at the official Microsoft Source ISO for this build (ADR-001 — WinMint"
say "never downloads or redistributes Windows media)."
ask SOURCE_ISO "Path to Source ISO:"
write_env SOURCE_ISO "$SOURCE_ISO"
if [[ -n "$SOURCE_ISO" && -f "$SOURCE_ISO" ]]; then
  printf '  %s✓%s found: %s\n' "$GREEN" "$RESET" "$SOURCE_ISO"
else
  warn "couldn't find that path from the current directory — double-check before Gate B."
fi

# ── Stage 4: Gate B + wipe ISO (one Release + package-strict Apply) ─────────
stage "Gate B + wipe ISO"
say "From the repo root, run Primary once (Release + package-strict)."
say "Workdir defaults to %LOCALAPPDATA%\\WinMint\\work\\gate-b (survives TEMP toolkit cleanup)."
step "just primary-gate ISO=$SOURCE_ISO"
note "This drives tools/apply/Invoke-HostApply.ps1 and can take multiple hours — one build only."
pause "Press Enter once that command has finished"
GATE_WORK="${LOCALAPPDATA:-$HOME/AppData/Local}/WinMint/work/gate-b"
if confirm "Does $GATE_WORK/apply-acceptance.json exist (Gate B green)?"; then
  printf '  %s✓%s Gate B acceptance evidence present\n' "$GREEN" "$RESET"
else
  warn "no Gate B evidence — do not proceed to a destructive install without it."
  exit 1
fi
WIPE_ISO=""
EVIDENCE="$GATE_WORK/evidence.json"
if [[ -f "$EVIDENCE" ]]; then
  WIPE_ISO=$(pwsh -NoProfile -Command "\$e = Get-Content -LiteralPath '$EVIDENCE' -Raw | ConvertFrom-Json; if (\$e.outputIsoPath) { \$e.outputIsoPath }" 2>/dev/null || true)
fi
if [[ -z "$WIPE_ISO" || ! -f "$WIPE_ISO" ]]; then
  WIPE_ISO=$(ls -1t "$GATE_WORK"/winmint_*.iso 2>/dev/null | head -n1 || true)
fi
if [[ -z "$WIPE_ISO" || ! -f "$WIPE_ISO" ]]; then
  WIPE_ISO="$GATE_WORK/out.iso"
fi
if [[ -f "$WIPE_ISO" ]]; then
  printf '  %s✓%s %s exists\n' "$GREEN" "$RESET" "$WIPE_ISO"
  write_env WIPE_ISO "$WIPE_ISO"
else
  warn "Output ISO not found under $GATE_WORK — the build likely failed. Do not flash a USB yet."
  exit 1
fi

# ── Stage 5: USB write ──────────────────────────────────────────────────────
stage "USB write"
say "Flash $WIPE_ISO to a USB drive with Rufus DD (or another honest ISO writer)."
note "Check digests: evidence.json outputIso.sha256 must match Get-FileHash on the Output ISO."
pause "Press Enter once the USB is flashed and ready"

# ── Stage 6: Destructive install ────────────────────────────────────────────
stage "Destructive install"
warn "This step WIPES the primary Surface Laptop 7. It is irreversible."
if ! confirm "Restore path confirmed AND you intend to wipe this PC now?"; then
  warn "stopping — re-run this wizard when you're ready."
  exit 1
fi
pause "Boot the SL7 from the USB and start the WinPE apply. Press Enter once it's running"
if ! confirm "Apply completed and the machine rebooted into OOBE/FirstLogon?"; then
  warn "apply did not complete cleanly — investigate before calling this gate met."
fi

# ── Stage 7: FirstLogon watch ───────────────────────────────────────────────
stage "FirstLogon watch"
say "Watch FirstLogon on the SL7 and confirm each of these in order:"
step "splash appears"
step "DMA settle reaches green (hard fields)"
step "AppX safetyNet completes online (session not Failed)"
step "Deprovisioned marks present for remove-list AppX (safetyNet / AppxAllUserStore)"
step "curated packages install under --package-strict: Cursor, Zen, WSL Fedora"
step "shell core: pwsh + Terminal + scoop toolbox + shell.stamp"
step "Explorer unlock happens"
pause "Press Enter once you've watched FirstLogon through to Explorer unlock"

# ── Stage 8: Evidence copy-off ──────────────────────────────────────────────
stage "Evidence copy-off"
say "Copy %ProgramData%\\WinMint\\evidence\\ off the SL7 before doing anything else."
ask EVIDENCE_DIR "Where did you copy the evidence to (path on this machine):"
write_env EVIDENCE_DIR "$EVIDENCE_DIR"

# ── Stage 9: Checklist assert ──────────────────────────────────────────────
stage "Checklist assert"
say "Eyeball packages.evidence.json in the copied evidence and confirm it shows"
say "the curated packages (Cursor, Zen, WSL Fedora) green with no failures."
say "Also confirm (reg query / evidence digests) FU posture still present after FirstLogon:"
step "HKLM ...\\CloudContent\\DisableWindowsConsumerFeatures = 1"
step "HKLM ...\\CloudContent\\DisableSoftLanding = 1"
step "HKLM ...\\WindowsStore\\AutoDownload = 2"
note "True FU survival needs a later Feature Update + re-check — record FirstLogon baseline now."
if confirm "packages.evidence.json green AND FU HKLM baseline present?"; then
  printf '  %s✓%s Primary wipe path looks met — commit or attach evidence in-repo when ready.\n' "$GREEN" "$RESET"
else
  warn "not green yet — do not treat Primary as proven without install evidence."
fi

finish
