watch_stylesheet: true
watch_config: true
debug: false
update_check: false
show_systray: false

bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: false
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 32
    widgets:
      left: ["home", "taskbar"]
      center: ["clock", "media"]
      right: ["systray", "volume", "settings", "notifications", "power_menu"]

widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue62a</span>"
      menu_labels:
        about: "\ue946  About this PC"
        system: "\uf423  System settings"
        task_manager: "\uf437  Task Manager"
        hibernate: "\uf28e  Hibernate"
        sleep: "\u23fe  Sleep"
        restart: "\uead2  Restart"
        shutdown: "\uf011  Shut down"
        lock: "\uea75  Lock"
        logout: "\udb80\udf43  Sign out"
      menu_list:
        - { title: "\ue617  Home", path: "~" }
        - { title: "\udb80\udd20  Downloads", path: "~\\Downloads" }
        - { title: "\udb80\ude1a  Documents", path: "~\\Documents" }
        - { title: "\uf03e  Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: "System"
      round_corners_type: "normal"

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 14
      tooltip: false
      show_only_visible: true
      strict_filtering: true
      monitor_exclusive: true
      animation:
        enabled: false
      preview:
        enabled: false
      ignore_apps:
        processes: []
        titles: []
        classes: []

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d %b %H:%M}"
      label_alt: "{%A, %d %B %Y, %H:%M}"
      locale: "en_US"
      callbacks:
        on_left: "toggle_calendar"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-clock:"
      calendar:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        show_holidays: false
        show_week_numbers: true

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: ""
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 34
        label_alt: 34
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 150
      thumbnail_padding: 12
      thumbnail_corner_radius: 8
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\ue76b"
      label_expanded: "\ue76c"
      label_position: "right"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: false
      show_battery: false
      show_volume: false
      show_network: true

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{icon} {level}"
      tooltip: false
      volume_icons:
        - "\ue992"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_middle: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"

  settings:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "\ue690", launch: "quick_settings" }

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\ue7f4</span> {count}"
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "do_nothing"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: true
      blur: false
      blur_background: true
      animation_duration: 220
      button_row: 3
      buttons:
        lock: ["\uea75", "Lock"]
        signout: ["\udb80\udf43", "Sign out"]
        shutdown: ["\uf011", "Shut down"]
        restart: ["\uead2", "Restart"]
        hibernate: ["\uf28e", "Hibernate"]
        cancel: ["\udb81\udf3a", "Cancel"]
